VIDEO_INPUT_PATH = "video/raw_video/record_2026-06-06_11-10-30.avi"
VIDEO_OUTPUT_PATH = "video/ppe_demo/ppe_output_video4.mp4"

POSE_MODEL_PATH = "yolo11x-pose.pt"
PPE_MODEL_PATH = "runs/detect/ppe-2class-6/weights/best.pt"

HAT_CLASS_ID = 1
VEST_CLASS_ID = 0

HELMET_CONF_THRES = 0.5
VEST_CONF_THRES = 0.5
PERSON_CONF_THRES = 0.6

POSE_IMGSZ = 640
PPE_IMGSZ = 640

HEAD_OVERLAP_THRES = 0.2
TORSO_OVERLAP_THRES = 0.25

DEBUG_MODE = False
DEBUG_RAW_PPE = True

TEMPORAL_WINDOW = 7
MIN_HISTORY_TO_DECIDE = 4
HELMET_SAFE_RATIO_THRES = 0.7
HELMET_VIOLATION_RATIO_THRES = 0.3
VEST_SAFE_RATIO_THRES = 0.5
VEST_VIOLATION_RATIO_THRES = 0.3

TRACK_IOU_THRES = 0.3
TRACK_TTL = 30
