import json

VIDEO_INPUT_PATH = "video/raw_video/record_2026-06-01_15-30-54.avi"
VIDEO_OUTPUT_PATH = "video/stair_demo/demo14.mp4"
CAMERA_CONFIG_PATH = "camera_config.json"
DEMO_MODE = True
SHOW_ONLY_VIOLATIONS = True
SHOW_PEOPLE_COUNT = True
DRAW_DEBUG = False
DRAW_DEBUG_DETAIL = False
DRAW_SAFE_STATUS = False
DRAW_SKELETON = False
DRAW_KEYPOINTS = False
SAVE_OUTPUT_VIDEO = True

SAFE_COLOR = (0, 255, 0)
VIOLATION_COLOR = (0, 0, 255)
UNKNOWN_COLOR = (0, 255, 255)
OUTSIDE_COLOR = (0, 255, 255)
ANALYZING_COLOR = (255, 255, 0)

LEFT_HANDRAIL_MAX_DISTANCE = 120
RIGHT_HANDRAIL_MAX_DISTANCE = 120
HANDRAIL_SEGMENT_MAX_DISTANCE = 100
WRONG_SIDE_HANDRAIL_SEGMENT_MAX_DISTANCE = 80
DIRECTION_SIGN_NORMAL = False
LANE_SIGN_NORMAL = True
LANE_HISTORY_LEN = 15
LANE_MIN_WRONG_HITS = 10
CARRY_ARM_ANGLE_THRESHOLD = 150
FRONT_CARRY_HISTORY_LEN = 18
FRONT_CARRY_MIN_HITS = 14
FRONT_CARRY_ONE_ARM_HISTORY_LEN = 30
FRONT_CARRY_ONE_ARM_MIN_HITS = 28
BACKWARD_HISTORY_LEN = 15
BACKWARD_MIN_HITS = 12
HOLD_HISTORY_LEN = 15
HOLD_MIN_NOT_HOLD_HITS = 10
HOLD_MIN_WRONG_SIDE_HITS = 5
WRIST_TOGETHER_THRESHOLD = 260
WRIST_TOGETHER_X_THRESHOLD = 180
WRIST_TOGETHER_Y_THRESHOLD = 260
DIRECTION_HISTORY_LEN = 20
DIRECTION_MIN_FRAMES = 12
DIRECTION_PIXEL_THRESHOLD = 25
STANDING_STILL_HISTORY_LEN = 18
STANDING_STILL_MIN_HITS = 14
STANDING_STILL_PIXEL_THRESHOLD = 20
STRONG_ONE_ARM_ANGLE_THRESHOLD = 145
STAIRS_LEFT_EXPAND_TOP_PX = 60
STAIRS_LEFT_EXPAND_BOTTOM_PX = 60


def load_camera_config(path=CAMERA_CONFIG_PATH):
    try:
        with open(path, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print("Khong tim thay file camera_config.json!")
        raise SystemExit(1)
