import json

VIDEO_INPUT_PATH = "video/record_2026-05-27_11-58-05.avi"
VIDEO_OUTPUT_PATH = "video/test_result11.mp4"
CAMERA_CONFIG_PATH = "camera_config.json"
DEMO_MODE = False
SHOW_ONLY_VIOLATIONS = False
SHOW_PEOPLE_COUNT = True
DRAW_DEBUG = True
DRAW_DEBUG_DETAIL = True
DRAW_SAFE_STATUS = True
DRAW_SKELETON = True
DRAW_KEYPOINTS = True
SAVE_OUTPUT_VIDEO = True

SAFE_COLOR = (0, 255, 0)
VIOLATION_COLOR = (0, 0, 255)
UNKNOWN_COLOR = (0, 255, 255)
OUTSIDE_COLOR = (0, 255, 255)
ANALYZING_COLOR = (255, 255, 0)

LEFT_HANDRAIL_MAX_DISTANCE = 120
RIGHT_HANDRAIL_MAX_DISTANCE = 120
HANDRAIL_SEGMENT_MAX_DISTANCE = 100
WRONG_SIDE_HANDRAIL_SEGMENT_MAX_DISTANCE = 80
DIRECTION_SIGN_NORMAL = False
LANE_SIGN_NORMAL = True
LANE_HISTORY_LEN = 15
LANE_MIN_WRONG_HITS = 10
CARRY_ARM_ANGLE_THRESHOLD = 150
FRONT_CARRY_HISTORY_LEN = 20
FRONT_CARRY_MIN_HITS = 14
FRONT_CARRY_ONE_ARM_HISTORY_LEN = 30
FRONT_CARRY_ONE_ARM_MIN_HITS = 24
BACKWARD_HISTORY_LEN = 24
BACKWARD_MIN_HITS = 16
HOLD_HISTORY_LEN = 15
HOLD_MIN_NOT_HOLD_HITS = 10
HOLD_MIN_WRONG_SIDE_HITS = 5
WRIST_TOGETHER_THRESHOLD = 260
WRIST_TOGETHER_X_THRESHOLD = 180
WRIST_TOGETHER_Y_THRESHOLD = 260
DIRECTION_HISTORY_LEN = 20
DIRECTION_MIN_FRAMES = 12
DIRECTION_PIXEL_THRESHOLD = 25
STRONG_ONE_ARM_ANGLE_THRESHOLD = 145
STAIRS_LEFT_EXPAND_TOP_PX = 60
STAIRS_LEFT_EXPAND_BOTTOM_PX = 60


def load_camera_config(path=CAMERA_CONFIG_PATH):
    try:
        with open(path, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print("Khong tim thay file camera_config.json!")
        raise SystemExit(1)
