import json

VIDEO_INPUT_PATH = "video/raw_video/record_2026-05-27_11-58-05.avi"
VIDEO_OUTPUT_PATH = "video/stair_demo/demo1.mp4"
CAMERA_CONFIG_PATH = "camera_config.json"
DEMO_MODE = True
SHOW_ONLY_VIOLATIONS = True
ENABLE_PERF_LOG = True
PERF_LOG_INTERVAL = 30
ENABLE_DEBUG_OVERLAY = False
ENABLE_VERBOSE_PERSON_DEBUG = False
ENABLE_SKELETON_DRAW = False
ENABLE_SUMMARY_PANEL = True
ENABLE_VIETNAMESE_TEXT = True
SHOW_PEOPLE_COUNT = ENABLE_SUMMARY_PANEL
DRAW_DEBUG = ENABLE_DEBUG_OVERLAY
DRAW_DEBUG_DETAIL = ENABLE_VERBOSE_PERSON_DEBUG
DRAW_SAFE_STATUS = False
DRAW_SKELETON = ENABLE_SKELETON_DRAW
DRAW_KEYPOINTS = ENABLE_DEBUG_OVERLAY
SAVE_OUTPUT_VIDEO = True

VIOLATION_DISPLAY_NAMES = {
    "Sai Lan": "Sai làn",
    "Khong Vin": "Không vịn",
    "Vin Sai Ben": "Vịn sai bên",
    "Mang Vac": "Mang vác",
    "Di Lui": "Đi lùi",
    "Dung Yen": "Đứng yên",
}
VIOLATION_COUNT_LABELS = [
    "Sai Lan",
    "Khong Vin",
    "Vin Sai Ben",
    "Mang Vac",
    "Di Lui",
    "Dung Yen",
]

SAFE_COLOR = (0, 255, 0)
VIOLATION_COLOR = (0, 0, 255)
UNKNOWN_COLOR = (0, 255, 255)
OUTSIDE_COLOR = (0, 255, 255)
ANALYZING_COLOR = (255, 255, 0)

LEFT_HANDRAIL_MAX_DISTANCE = 120
RIGHT_HANDRAIL_MAX_DISTANCE = 120
HANDRAIL_SEGMENT_MAX_DISTANCE = 100
WRONG_SIDE_HANDRAIL_SEGMENT_MAX_DISTANCE = 80
DIRECTION_SIGN_NORMAL = False
LANE_SIGN_NORMAL = True
LANE_HISTORY_LEN = 15
LANE_MIN_WRONG_HITS = 10
CARRY_ARM_ANGLE_THRESHOLD = 150
FRONT_CARRY_HISTORY_LEN = 18
FRONT_CARRY_MIN_HITS = 14
FRONT_CARRY_ONE_ARM_HISTORY_LEN = 20
FRONT_CARRY_ONE_ARM_MIN_HITS = 16
WRIST_TOGETHER_X_RATIO = 1.2
WRIST_TOGETHER_Y_RATIO = 0.75
WRIST_TO_TORSO_X_RATIO = 0.1
WRIST_TO_TORSO_Y_RATIO = 0.25
ELBOW_TO_TORSO_X_RATIO = 0
CARRY_REGION_MARGIN_RATIO = 0.15
MIN_WRIST_TOGETHER_X_PX = 20
MIN_WRIST_TOGETHER_Y_PX = 20
MIN_WRIST_TO_TORSO_X_PX = 10
MIN_WRIST_TO_TORSO_Y_PX = 10
MIN_CARRY_REGION_MARGIN_PX = 10
BACKWARD_HISTORY_LEN = 15
BACKWARD_MIN_HITS = 9
HOLD_HISTORY_LEN = 15
HOLD_MIN_NOT_HOLD_HITS = 12
HOLD_MIN_NOT_HOLD_EVIDENCE_HITS = 15
HOLD_MIN_WRONG_SIDE_HITS = 10
WRIST_TOGETHER_THRESHOLD = 260
WRIST_TOGETHER_X_THRESHOLD = 180
WRIST_TOGETHER_Y_THRESHOLD = 260
DIRECTION_HISTORY_LEN = 20
DIRECTION_MIN_FRAMES = 12
DIRECTION_PIXEL_THRESHOLD = 25
STANDING_STILL_HISTORY_LEN = 18
STANDING_STILL_MIN_HITS = 14
STANDING_STILL_PIXEL_THRESHOLD = 30
STRONG_ONE_ARM_ANGLE_THRESHOLD = 145
STAIRS_LEFT_EXPAND_TOP_PX = 60
STAIRS_LEFT_EXPAND_BOTTOM_PX = 60


def load_camera_config(path=CAMERA_CONFIG_PATH):
    try:
        with open(path, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print("Khong tim thay file camera_config.json!")
        raise SystemExit(1)
